const translations = {
  en: {
    "nav.features": "Features",
    "nav.support": "Support",
    "nav.privacy": "Privacy",
    "hero.eyebrow": "iPhone app",
    "hero.title": "Sidequest",
    "hero.text": "Life is short. Do something weird with it.",
    "hero.cta": "Download on the App Store",
    "hero.support": "Get support",
    "preview.title": "Your side quest is:",
    "preview.category": "Exploration",
    "preview.difficulty": "Mildly Inconvenient",
    "preview.questTitle": "Find the best coffee in a city that is not yours",
    "preview.questText": "Ask a local. Not Google.",
    "preview.question": "Do you accept?",
    "preview.yes": "YES",
    "preview.no": "NO",
    "features.eyebrow": "What it does",
    "features.title": "A tiny push into the real world.",
    "features.generate.title": "Generate quests",
    "features.generate.text": "Get concrete challenges across social, culinary, physical, creative, exploration, mechanical, and random categories.",
    "features.chronicles.title": "Build chronicles",
    "features.chronicles.text": "Capture quest moments with notes and up to six photos per entry, then replay them in a full-screen chronicle view.",
    "features.badges.title": "Unlock badges",
    "features.badges.text": "Complete quests, build a history, and earn badges for the choices you can explain later.",
    "features.memory.title": "Save the story",
    "features.memory.text": "Add a photo and note when a quest is complete, then keep it in your history or share it.",
    "features.widget.title": "Glance at the quest",
    "features.widget.text": "Keep the active quest visible with the iOS widget and Live Activity support.",
    "features.filters.title": "Control the pool",
    "features.filters.text": "Choose categories and difficulty levels, and block keywords you do not want to see.",
    "features.premium.title": "Unlock Premium",
    "features.premium.text": "Premium unlocks Bat Shit Crazy difficulty, exclusive BSC drops, and future quest packs.",
    "premium.eyebrow": "Premium",
    "premium.title": "Unlock the chaos.",
    "premium.text": "The free quests are the safe stuff. Premium is where Sidequest gets interesting.",
    "premium.chip1": "Bat Shit Crazy difficulty",
    "premium.chip2": "Exclusive BSC quest drops",
    "premium.chip3": "Future quest packs included",
    "levels.eyebrow": "Difficulty levels",
    "levels.title": "From harmless to highly questionable.",
    "levels.text": "Tune your comfort zone. Sidequest supports four difficulty tiers, with Bat Shit Crazy available through Premium.",
    "levels.safe": "Fun & Safe",
    "levels.mild": "Mildly Inconvenient",
    "levels.probably": "Probably Shouldn't",
    "levels.bsc": "Bat Shit Crazy",
    "download.title": "Available on the App Store.",
    "download.text": "Download Sidequest for iPhone and start your next real-world quest.",
    "download.button": "Open App Store",
    "footer.support": "Support",
    "footer.marketing": "Marketing page",
    "footer.privacy": "Privacy",
    "support.eyebrow": "Support",
    "support.title": "Sidequest Support",
    "support.intro": "Need help with the app, subscriptions, quest history, badges, or something that feels off? Start here.",
    "support.contact.title": "Contact",
    "support.contact.text": "For app support, include your device model, iOS version, and a short description of the issue.",
    "support.contact.button": "Email support",
    "support.contact.note": "Current support email: pcesnek290@gmail.com",
    "support.restore.title": "Purchases",
    "support.restore.text": "If premium access is missing after reinstalling or changing devices, open Sidequest settings and use Restore Purchases.",
    "support.data.title": "Photos and history",
    "support.data.text": "Quest history, notes, badges, and chronicle entries are stored on your device. Chronicle photos use your iOS Photos library.",
    "support.safety.title": "Quest safety",
    "support.safety.text": "Use judgement, follow local laws, and skip any quest that feels unsafe, illegal, or inappropriate for your situation.",
    "support.remote.title": "Quest packs",
    "support.remote.text": "Sidequest may download the latest quest pool from the Sidequest quest repository. If the network is unavailable, the app can use bundled or cached quests.",
    "support.activity.title": "Widget and Live Activity",
    "support.activity.text": "If an active quest is not visible in the widget or Live Activity, open the app once and start or restore the current quest.",
    "faq.title": "FAQ",
    "faq.block.summary": "Can I block quests I do not want?",
    "faq.block.text": "Yes. In settings, you can disable categories or add blocked keywords.",
    "faq.languages.summary": "Which languages are supported?",
    "faq.languages.text": "Sidequest is localized in English, Czech, Slovak, German, Spanish, and Portuguese.",
    "faq.widget.summary": "Does Sidequest have a widget?",
    "faq.widget.text": "Yes. The widget and Live Activity can show your current active quest at a glance.",
    "faq.premium.summary": "What does Premium unlock?",
    "faq.premium.text": "Premium unlocks Bat Shit Crazy difficulty, exclusive BSC quest drops, and future quest packs.",
    "privacy.eyebrow": "Privacy",
    "privacy.title": "Privacy Policy",
    "privacy.updated": "Last updated: June 19, 2026",
    "privacy.overview.title": "Overview",
    "privacy.overview.text": "Sidequest is designed to keep your personal quest activity on your device. We do not run our own account system, advertising network, or analytics service in the app.",
    "privacy.collect.summary": "Information the app stores",
    "privacy.collect.text": "Sidequest may store your display name, preferences, generated quests, active quest state, quest history, badges, blocked keywords, notes, chronicle entries, and photo references locally on your device so the app can work.",
    "privacy.photos.summary": "Photos and camera access",
    "privacy.photos.text": "If you choose to add photos to a quest or chronicle entry, Sidequest uses camera or photo library access only for that action. Chronicle entries may store local Photos library identifiers so the app can show those photos later.",
    "privacy.remote.summary": "Quest downloads",
    "privacy.remote.text": "Sidequest may contact the Sidequest quest repository to download the latest quest pool and cache it on your device. This request is for app content, not user account sync.",
    "privacy.purchases.summary": "Purchases and subscriptions",
    "privacy.purchases.text": "Premium purchases are processed by Apple through the App Store. Sidequest may read your App Store purchase status to unlock premium features, but payment details are handled by Apple.",
    "privacy.support.summary": "Support email",
    "privacy.support.text": "If you contact support by email, we receive the information you choose to send, such as your email address, device details, and message. We use it only to respond to your request.",
    "privacy.third.summary": "Third parties",
    "privacy.third.text": "Sidequest uses Apple services such as the App Store and iOS system features. Those services are governed by Apple's privacy policies. We do not sell your personal information.",
    "privacy.delete.summary": "Deleting your data",
    "privacy.delete.text": "Most app data is stored locally. You can remove it by deleting the app from your device. You can also contact support if you have questions about information sent by email.",
    "privacy.contact.summary": "Contact",
    "privacy.contact.text": "For privacy questions, email pcesnek290@gmail.com.",
    "quest.title": "You've been challenged ⚔️",
    "quest.text": "A friend dares you to do this quest. Opening Sidequest…",
    "quest.open": "Open in the app",
    "quest.store": "Don't have Sidequest? Get it on the App Store"
  },
  cs: {
    "nav.features": "Funkce",
    "nav.support": "Podpora",
    "nav.privacy": "Soukromí",
    "hero.eyebrow": "iPhone aplikace",
    "hero.title": "Sidequest",
    "hero.text": "Život je krátký. Udělej s ním něco divného.",
    "hero.cta": "Stáhnout v App Storu",
    "hero.support": "Získat podporu",
    "preview.title": "Tvůj sidequest je:",
    "preview.category": "Průzkum",
    "preview.difficulty": "Mírně nepohodlné",
    "preview.questTitle": "Najdi nejlepší kávu ve městě, které není tvoje",
    "preview.questText": "Zeptej se místního. Ne Googlu.",
    "preview.question": "Přijímáš?",
    "preview.yes": "ANO",
    "preview.no": "NE",
    "features.eyebrow": "Co umí",
    "features.title": "Malé pošťouchnutí do skutečného světa.",
    "features.generate.title": "Generuj questy",
    "features.generate.text": "Získej konkrétní výzvy ze sociálních, kulinářských, fyzických, kreativních, průzkumných, mechanických a náhodných kategorií.",
    "features.chronicles.title": "Buduj kroniky",
    "features.chronicles.text": "Zachycuj okamžiky z questů pomocí poznámek a až šesti fotek v jednom záznamu, potom si je přehraj v celoobrazovkové kronice.",
    "features.badges.title": "Odemykej odznaky",
    "features.badges.text": "Plň questy, buduj historii a sbírej odznaky za rozhodnutí, která později zvládneš vysvětlit.",
    "features.memory.title": "Ulož si příběh",
    "features.memory.text": "Po dokončení přidej fotku a poznámku, nech si je v historii nebo je sdílej.",
    "features.widget.title": "Měj quest na očích",
    "features.widget.text": "Aktivní quest můžeš mít po ruce díky iOS widgetu a podpoře Live Activity.",
    "features.filters.title": "Ovládej výběr",
    "features.filters.text": "Vyber si kategorie a obtížnosti a blokuj klíčová slova, která nechceš vidět.",
    "features.premium.title": "Odemkni Premium",
    "features.premium.text": "Premium odemyká obtížnost Bat Shit Crazy, exkluzivní BSC dropy a budoucí balíčky questů.",
    "premium.eyebrow": "Premium",
    "premium.title": "Odemkni chaos.",
    "premium.text": "Bezplatné questy jsou ta bezpečná varianta. Premium je místo, kde Sidequest začíná být zajímavý.",
    "premium.chip1": "Obtížnost Bat Shit Crazy",
    "premium.chip2": "Exkluzivní BSC quest dropy",
    "premium.chip3": "Budoucí balíčky questů v ceně",
    "levels.eyebrow": "Obtížnosti",
    "levels.title": "Od neškodného po silně pochybné.",
    "levels.text": "Nastav si komfortní zónu. Sidequest podporuje čtyři úrovně obtížnosti, přičemž Bat Shit Crazy je dostupná přes Premium.",
    "levels.safe": "Zábavné a bezpečné",
    "levels.mild": "Mírně nepohodlné",
    "levels.probably": "Radši asi ne",
    "levels.bsc": "Šílené",
    "download.title": "Dostupné v App Storu.",
    "download.text": "Stáhni si Sidequest pro iPhone a začni svůj další quest ve skutečném světě.",
    "download.button": "Otevřít App Store",
    "footer.support": "Podpora",
    "footer.marketing": "Marketingová stránka",
    "footer.privacy": "Soukromí",
    "support.eyebrow": "Podpora",
    "support.title": "Podpora Sidequest",
    "support.intro": "Potřebuješ pomoc s aplikací, předplatným, historií questů, odznaky nebo něčím, co nefunguje správně? Začni tady.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Pro podporu uveď model zařízení, verzi iOS a krátký popis problému.",
    "support.contact.button": "Napsat podpoře",
    "support.contact.note": "Aktuální e-mail podpory: pcesnek290@gmail.com",
    "support.restore.title": "Nákupy",
    "support.restore.text": "Pokud po přeinstalaci nebo změně zařízení chybí premium přístup, otevři nastavení Sidequestu a použij Obnovit nákupy.",
    "support.data.title": "Fotky a historie",
    "support.data.text": "Historie questů, poznámky, odznaky a záznamy kronik jsou uložené v zařízení. Fotky v kronikách používají tvoji knihovnu Fotky v iOS.",
    "support.safety.title": "Bezpečnost questů",
    "support.safety.text": "Používej úsudek, dodržuj místní zákony a přeskoč každý quest, který je nebezpečný, nelegální nebo nevhodný pro tvoji situaci.",
    "support.remote.title": "Balíčky questů",
    "support.remote.text": "Sidequest může stáhnout nejnovější výběr questů z repozitáře questů Sidequest. Pokud síť není dostupná, aplikace může použít vestavěné nebo uložené questy.",
    "support.activity.title": "Widget a Live Activity",
    "support.activity.text": "Pokud se aktivní quest nezobrazuje ve widgetu nebo Live Activity, jednou otevři aplikaci a spusť nebo obnov aktuální quest.",
    "faq.title": "FAQ",
    "faq.block.summary": "Můžu blokovat questy, které nechci?",
    "faq.block.text": "Ano. V nastavení můžeš vypnout kategorie nebo přidat blokovaná klíčová slova.",
    "faq.languages.summary": "Jaké jazyky aplikace podporuje?",
    "faq.languages.text": "Sidequest je lokalizovaný do angličtiny, češtiny, slovenštiny, němčiny, španělštiny a portugalštiny.",
    "faq.widget.summary": "Má Sidequest widget?",
    "faq.widget.text": "Ano. Widget a Live Activity umí zobrazit aktuální aktivní quest na první pohled.",
    "faq.premium.summary": "Co odemyká Premium?",
    "faq.premium.text": "Premium odemyká obtížnost Bat Shit Crazy, exkluzivní BSC quest dropy a budoucí balíčky questů.",
    "privacy.eyebrow": "Soukromí",
    "privacy.title": "Zásady ochrany soukromí",
    "privacy.updated": "Naposledy aktualizováno: 19. června 2026",
    "privacy.overview.title": "Přehled",
    "privacy.overview.text": "Sidequest je navržený tak, aby tvoje osobní aktivita v questech zůstávala v zařízení. V aplikaci neprovozujeme vlastní systém účtů, reklamní síť ani analytickou službu.",
    "privacy.collect.summary": "Informace uložené aplikací",
    "privacy.collect.text": "Sidequest může lokálně v zařízení ukládat tvoje zobrazované jméno, preference, vygenerované questy, stav aktivního questu, historii questů, odznaky, blokovaná klíčová slova, poznámky, záznamy kronik a odkazy na fotky, aby aplikace mohla fungovat.",
    "privacy.photos.summary": "Fotky a přístup ke kameře",
    "privacy.photos.text": "Pokud se rozhodneš přidat fotky ke questu nebo záznamu kroniky, Sidequest používá přístup ke kameře nebo knihovně fotek pouze pro tuto akci. Záznamy kronik mohou ukládat lokální identifikátory z knihovny Fotky, aby aplikace mohla fotky později zobrazit.",
    "privacy.remote.summary": "Stahování questů",
    "privacy.remote.text": "Sidequest může kontaktovat repozitář questů Sidequest, stáhnout nejnovější výběr questů a uložit ho do cache v zařízení. Tento požadavek slouží pro obsah aplikace, ne pro synchronizaci uživatelského účtu.",
    "privacy.purchases.summary": "Nákupy a předplatná",
    "privacy.purchases.text": "Prémiové nákupy zpracovává Apple prostřednictvím App Storu. Sidequest může číst stav nákupu z App Storu pro odemčení prémiových funkcí, ale platební údaje zpracovává Apple.",
    "privacy.support.summary": "E-mail podpory",
    "privacy.support.text": "Pokud kontaktuješ podporu e-mailem, obdržíme informace, které se rozhodneš poslat, například e-mailovou adresu, údaje o zařízení a zprávu. Použijeme je pouze k odpovědi na tvůj požadavek.",
    "privacy.third.summary": "Třetí strany",
    "privacy.third.text": "Sidequest používá služby Apple, například App Store a systémové funkce iOS. Tyto služby se řídí zásadami ochrany soukromí společnosti Apple. Tvoje osobní informace neprodáváme.",
    "privacy.delete.summary": "Smazání dat",
    "privacy.delete.text": "Většina dat aplikace je uložená lokálně. Můžeš je odstranit smazáním aplikace ze zařízení. Pokud máš otázky k informacím poslaným e-mailem, můžeš kontaktovat podporu.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "S otázkami k soukromí napiš na pcesnek290@gmail.com.",
    "quest.title": "Máš výzvu ⚔️",
    "quest.text": "Kamarád tě vyzývá na tenhle quest. Otevírám Sidequest…",
    "quest.open": "Otevřít v aplikaci",
    "quest.store": "Nemáš Sidequest? Stáhni ho v App Storu"
  },
  sk: {
    "nav.features": "Funkcie",
    "nav.support": "Podpora",
    "nav.privacy": "Súkromie",
    "hero.eyebrow": "iPhone aplikácia",
    "hero.title": "Sidequest",
    "hero.text": "Život je krátky. Urob s ním niečo zvláštne.",
    "hero.cta": "Stiahnuť v App Store",
    "hero.support": "Získať podporu",
    "preview.title": "Tvoj sidequest je:",
    "preview.category": "Prieskum",
    "preview.difficulty": "Mierne nepohodlné",
    "preview.questTitle": "Nájdi najlepšiu kávu v meste, ktoré nie je tvoje",
    "preview.questText": "Spýtaj sa miestneho. Nie Googlu.",
    "preview.question": "Prijímaš?",
    "preview.yes": "ÁNO",
    "preview.no": "NIE",
    "features.eyebrow": "Čo robí",
    "features.title": "Malé postrčenie do skutočného sveta.",
    "features.generate.title": "Generuj questy",
    "features.generate.text": "Získaj konkrétne výzvy zo sociálnych, kulinárskych, fyzických, kreatívnych, prieskumných, mechanických a náhodných kategórií.",
    "features.chronicles.title": "Buduj kroniky",
    "features.chronicles.text": "Zachytávaj okamihy z questov pomocou poznámok a až šiestich fotiek v jednom zázname, potom si ich prehraj v celoobrazovkovej kronike.",
    "features.badges.title": "Odomykaj odznaky",
    "features.badges.text": "Plň questy, buduj históriu a získavaj odznaky za rozhodnutia, ktoré neskôr zvládneš vysvetliť.",
    "features.memory.title": "Ulož si príbeh",
    "features.memory.text": "Po dokončení pridaj fotku a poznámku, nechaj si ich v histórii alebo ich zdieľaj.",
    "features.widget.title": "Maj quest na očiach",
    "features.widget.text": "Aktívny quest môžeš mať poruke vďaka iOS widgetu a podpore Live Activity.",
    "features.filters.title": "Ovládaj výber",
    "features.filters.text": "Vyber si kategórie a obtiažnosti a blokuj kľúčové slová, ktoré nechceš vidieť.",
    "features.premium.title": "Odomkni Premium",
    "features.premium.text": "Premium odomyká obtiažnosť Bat Shit Crazy, exkluzívne BSC dropy a budúce balíčky questov.",
    "premium.eyebrow": "Premium",
    "premium.title": "Odomkni chaos.",
    "premium.text": "Bezplatné questy sú tá bezpečná verzia. Premium je miesto, kde Sidequest začína byť zaujímavý.",
    "premium.chip1": "Obtiažnosť Bat Shit Crazy",
    "premium.chip2": "Exkluzívne BSC quest dropy",
    "premium.chip3": "Budúce balíčky questov v cene",
    "levels.eyebrow": "Obtiažnosti",
    "levels.title": "Od neškodného po silne otázne.",
    "levels.text": "Nastav si komfortnú zónu. Sidequest podporuje štyri úrovne obtiažnosti, pričom Bat Shit Crazy je dostupná cez Premium.",
    "levels.safe": "Zábavné a bezpečné",
    "levels.mild": "Mierne nepohodlné",
    "levels.probably": "Radšej asi nie",
    "levels.bsc": "Šialené",
    "download.title": "Dostupné v App Store.",
    "download.text": "Stiahni si Sidequest pre iPhone a začni svoj ďalší quest v skutočnom svete.",
    "download.button": "Otvoriť App Store",
    "footer.support": "Podpora",
    "footer.marketing": "Marketingová stránka",
    "footer.privacy": "Súkromie",
    "support.eyebrow": "Podpora",
    "support.title": "Podpora Sidequest",
    "support.intro": "Potrebuješ pomoc s aplikáciou, predplatným, históriou questov, odznakmi alebo niečím, čo nefunguje správne? Začni tu.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Pre podporu uveď model zariadenia, verziu iOS a krátky popis problému.",
    "support.contact.button": "Napísať podpore",
    "support.contact.note": "Aktuálny e-mail podpory: pcesnek290@gmail.com",
    "support.restore.title": "Nákupy",
    "support.restore.text": "Ak po preinštalovaní alebo zmene zariadenia chýba premium prístup, otvor nastavenia Sidequestu a použi Obnoviť nákupy.",
    "support.data.title": "Fotky a história",
    "support.data.text": "História questov, poznámky, odznaky a záznamy kroník sú uložené v zariadení. Fotky v kronikách používajú tvoju knižnicu Fotky v iOS.",
    "support.safety.title": "Bezpečnosť questov",
    "support.safety.text": "Používaj úsudok, dodržiavaj miestne zákony a preskoč každý quest, ktorý je nebezpečný, nelegálny alebo nevhodný pre tvoju situáciu.",
    "support.remote.title": "Balíčky questov",
    "support.remote.text": "Sidequest môže stiahnuť najnovší výber questov z repozitára questov Sidequest. Ak sieť nie je dostupná, aplikácia môže použiť vstavané alebo uložené questy.",
    "support.activity.title": "Widget a Live Activity",
    "support.activity.text": "Ak sa aktívny quest nezobrazuje vo widgete alebo Live Activity, raz otvor aplikáciu a spusti alebo obnov aktuálny quest.",
    "faq.title": "FAQ",
    "faq.block.summary": "Môžem blokovať questy, ktoré nechcem?",
    "faq.block.text": "Áno. V nastaveniach môžeš vypnúť kategórie alebo pridať blokované kľúčové slová.",
    "faq.languages.summary": "Aké jazyky aplikácia podporuje?",
    "faq.languages.text": "Sidequest je lokalizovaný do angličtiny, češtiny, slovenčiny, nemčiny, španielčiny a portugalčiny.",
    "faq.widget.summary": "Má Sidequest widget?",
    "faq.widget.text": "Áno. Widget a Live Activity vedia zobraziť aktuálny aktívny quest na prvý pohľad.",
    "faq.premium.summary": "Čo odomyká Premium?",
    "faq.premium.text": "Premium odomyká obtiažnosť Bat Shit Crazy, exkluzívne BSC quest dropy a budúce balíčky questov.",
    "privacy.eyebrow": "Súkromie",
    "privacy.title": "Zásady ochrany súkromia",
    "privacy.updated": "Naposledy aktualizované: 19. júna 2026",
    "privacy.overview.title": "Prehľad",
    "privacy.overview.text": "Sidequest je navrhnutý tak, aby tvoja osobná aktivita v questoch zostávala v zariadení. V aplikácii neprevádzkujeme vlastný systém účtov, reklamnú sieť ani analytickú službu.",
    "privacy.collect.summary": "Informácie uložené aplikáciou",
    "privacy.collect.text": "Sidequest môže lokálne v zariadení ukladať tvoje zobrazované meno, preferencie, vygenerované questy, stav aktívneho questu, históriu questov, odznaky, blokované kľúčové slová, poznámky, záznamy kroník a odkazy na fotky, aby aplikácia mohla fungovať.",
    "privacy.photos.summary": "Fotky a prístup ku kamere",
    "privacy.photos.text": "Ak sa rozhodneš pridať fotky ku questu alebo záznamu kroniky, Sidequest používa prístup ku kamere alebo knižnici fotiek iba na túto akciu. Záznamy kroník môžu ukladať lokálne identifikátory z knižnice Fotky, aby aplikácia mohla fotky neskôr zobraziť.",
    "privacy.remote.summary": "Sťahovanie questov",
    "privacy.remote.text": "Sidequest môže kontaktovať repozitár questov Sidequest, stiahnuť najnovší výber questov a uložiť ho do cache v zariadení. Táto požiadavka slúži pre obsah aplikácie, nie pre synchronizáciu používateľského účtu.",
    "privacy.purchases.summary": "Nákupy a predplatné",
    "privacy.purchases.text": "Prémiové nákupy spracúva Apple prostredníctvom App Store. Sidequest môže čítať stav nákupu z App Store na odomknutie prémiových funkcií, ale platobné údaje spracúva Apple.",
    "privacy.support.summary": "E-mail podpory",
    "privacy.support.text": "Ak kontaktuješ podporu e-mailom, dostaneme informácie, ktoré sa rozhodneš poslať, napríklad e-mailovú adresu, údaje o zariadení a správu. Použijeme ich iba na odpoveď na tvoju požiadavku.",
    "privacy.third.summary": "Tretie strany",
    "privacy.third.text": "Sidequest používa služby Apple, napríklad App Store a systémové funkcie iOS. Tieto služby sa riadia zásadami ochrany súkromia spoločnosti Apple. Tvoje osobné informácie nepredávame.",
    "privacy.delete.summary": "Vymazanie dát",
    "privacy.delete.text": "Väčšina dát aplikácie je uložená lokálne. Môžeš ich odstrániť vymazaním aplikácie zo zariadenia. Ak máš otázky k informáciám poslaným e-mailom, môžeš kontaktovať podporu.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "S otázkami k súkromiu napíš na pcesnek290@gmail.com.",
    "quest.title": "Máš výzvu ⚔️",
    "quest.text": "Kamarát ťa vyzýva na tento quest. Otváram Sidequest…",
    "quest.open": "Otvoriť v aplikácii",
    "quest.store": "Nemáš Sidequest? Stiahni ho v App Store"
  },
  de: {
    "nav.features": "Funktionen",
    "nav.support": "Support",
    "nav.privacy": "Datenschutz",
    "hero.eyebrow": "iPhone-App",
    "hero.title": "Sidequest",
    "hero.text": "Das Leben ist kurz. Mach was Verrücktes draus.",
    "hero.cta": "Im App Store laden",
    "hero.support": "Support erhalten",
    "preview.title": "Dein Sidequest ist:",
    "preview.category": "Erkundung",
    "preview.difficulty": "Leicht unbequem",
    "preview.questTitle": "Finde den besten Kaffee in einer fremden Stadt",
    "preview.questText": "Frag Einheimische. Nicht Google.",
    "preview.question": "Nimmst du an?",
    "preview.yes": "JA",
    "preview.no": "NEIN",
    "features.eyebrow": "Was es kann",
    "features.title": "Ein kleiner Schubs in die echte Welt.",
    "features.generate.title": "Quests generieren",
    "features.generate.text": "Erhalte konkrete Challenges aus den Kategorien Sozial, Kulinarisch, Körperlich, Kreativ, Erkundung, Mechanisch und Zufall.",
    "features.chronicles.title": "Chroniken erstellen",
    "features.chronicles.text": "Halte Quest-Momente mit Notizen und bis zu sechs Fotos pro Eintrag fest und erlebe sie in der Vollbild-Chronik neu.",
    "features.badges.title": "Erfolge freischalten",
    "features.badges.text": "Schließe Quests ab, bau deinen Verlauf auf und verdiene Erfolge für die Entscheidungen, die du später erklären kannst.",
    "features.memory.title": "Die Geschichte sichern",
    "features.memory.text": "Füge nach einem Quest ein Foto und eine Notiz hinzu, behalte alles im Verlauf oder teile es.",
    "features.widget.title": "Quest im Blick",
    "features.widget.text": "Behalte den aktiven Quest mit dem iOS-Widget und Live Activities im Blick.",
    "features.filters.title": "Den Pool steuern",
    "features.filters.text": "Wähle Kategorien und Schwierigkeitsgrade und blockiere Wörter, die du nicht sehen willst.",
    "features.premium.title": "Premium freischalten",
    "features.premium.text": "Premium schaltet die Schwierigkeit Total durchgeknallt, exklusive BSC-Drops und zukünftige Quest-Packs frei.",
    "premium.eyebrow": "Premium",
    "premium.title": "Entfessle das Chaos.",
    "premium.text": "Die kostenlosen Quests sind der harmlose Teil. Mit Premium wird Sidequest interessant.",
    "premium.chip1": "Schwierigkeit Total durchgeknallt",
    "premium.chip2": "Exklusive BSC-Quest-Drops",
    "premium.chip3": "Zukünftige Quest-Packs inklusive",
    "levels.eyebrow": "Schwierigkeitsgrade",
    "levels.title": "Von harmlos bis höchst fragwürdig.",
    "levels.text": "Justiere deine Komfortzone. Sidequest bietet vier Schwierigkeitsstufen — Total durchgeknallt gibt es mit Premium.",
    "levels.safe": "Spaß & Sicher",
    "levels.mild": "Leicht unbequem",
    "levels.probably": "Solltest du eher nicht",
    "levels.bsc": "Total durchgeknallt",
    "download.title": "Verfügbar im App Store.",
    "download.text": "Lade Sidequest für iPhone und starte deinen nächsten Quest in der echten Welt.",
    "download.button": "App Store öffnen",
    "footer.support": "Support",
    "footer.marketing": "Marketing-Seite",
    "footer.privacy": "Datenschutz",
    "support.eyebrow": "Support",
    "support.title": "Sidequest Support",
    "support.intro": "Brauchst du Hilfe mit der App, Abos, dem Quest-Verlauf, Erfolgen oder etwas, das sich falsch anfühlt? Fang hier an.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Für App-Support gib dein Gerätemodell, die iOS-Version und eine kurze Beschreibung des Problems an.",
    "support.contact.button": "Support per E-Mail",
    "support.contact.note": "Aktuelle Support-E-Mail: pcesnek290@gmail.com",
    "support.restore.title": "Käufe",
    "support.restore.text": "Wenn Premium nach einer Neuinstallation oder einem Gerätewechsel fehlt, öffne die Sidequest-Einstellungen und nutze „Käufe wiederherstellen“.",
    "support.data.title": "Fotos und Verlauf",
    "support.data.text": "Quest-Verlauf, Notizen, Erfolge und Chronik-Einträge werden auf deinem Gerät gespeichert. Chronik-Fotos nutzen deine iOS-Fotomediathek.",
    "support.safety.title": "Quest-Sicherheit",
    "support.safety.text": "Nutze deinen Verstand, halte dich an lokale Gesetze und überspring jeden Quest, der sich unsicher, illegal oder unpassend anfühlt.",
    "support.remote.title": "Quest-Packs",
    "support.remote.text": "Sidequest kann den neuesten Quest-Pool aus dem Sidequest-Quest-Repository laden. Ohne Netzwerk nutzt die App gebündelte oder gecachte Quests.",
    "support.activity.title": "Widget und Live Activity",
    "support.activity.text": "Wenn ein aktiver Quest nicht im Widget oder in der Live Activity erscheint, öffne die App einmal und starte oder stelle den aktuellen Quest wieder her.",
    "faq.title": "FAQ",
    "faq.block.summary": "Kann ich Quests blockieren, die ich nicht will?",
    "faq.block.text": "Ja. In den Einstellungen kannst du Kategorien deaktivieren oder blockierte Wörter hinzufügen.",
    "faq.languages.summary": "Welche Sprachen werden unterstützt?",
    "faq.languages.text": "Sidequest ist auf Englisch, Tschechisch, Slowakisch, Deutsch, Spanisch und Portugiesisch lokalisiert.",
    "faq.widget.summary": "Hat Sidequest ein Widget?",
    "faq.widget.text": "Ja. Widget und Live Activity zeigen deinen aktuellen Quest auf einen Blick.",
    "faq.premium.summary": "Was schaltet Premium frei?",
    "faq.premium.text": "Premium schaltet die Schwierigkeit Total durchgeknallt, exklusive BSC-Quest-Drops und zukünftige Quest-Packs frei.",
    "privacy.eyebrow": "Datenschutz",
    "privacy.title": "Datenschutzerklärung",
    "privacy.updated": "Zuletzt aktualisiert: 19. Juni 2026",
    "privacy.overview.title": "Überblick",
    "privacy.overview.text": "Sidequest ist so gebaut, dass deine persönliche Quest-Aktivität auf deinem Gerät bleibt. Wir betreiben in der App kein eigenes Kontosystem, kein Werbenetzwerk und keinen Analysedienst.",
    "privacy.collect.summary": "Informationen, die die App speichert",
    "privacy.collect.text": "Sidequest kann deinen Anzeigenamen, Präferenzen, generierte Quests, den aktiven Quest-Status, den Quest-Verlauf, Erfolge, blockierte Wörter, Notizen, Chronik-Einträge und Foto-Referenzen lokal auf deinem Gerät speichern, damit die App funktioniert.",
    "privacy.photos.summary": "Fotos und Kamerazugriff",
    "privacy.photos.text": "Wenn du einem Quest oder Chronik-Eintrag Fotos hinzufügst, nutzt Sidequest den Kamera- oder Mediathek-Zugriff nur für diese Aktion. Chronik-Einträge können lokale Foto-Identifikatoren speichern, damit die App die Fotos später anzeigen kann.",
    "privacy.remote.summary": "Quest-Downloads",
    "privacy.remote.text": "Sidequest kann das Sidequest-Quest-Repository kontaktieren, um den neuesten Quest-Pool zu laden und auf deinem Gerät zu cachen. Diese Anfrage dient dem App-Inhalt, nicht der Synchronisierung eines Nutzerkontos.",
    "privacy.purchases.summary": "Käufe und Abos",
    "privacy.purchases.text": "Premium-Käufe werden von Apple über den App Store abgewickelt. Sidequest kann deinen App-Store-Kaufstatus lesen, um Premium-Funktionen freizuschalten — Zahlungsdaten verarbeitet Apple.",
    "privacy.support.summary": "Support-E-Mail",
    "privacy.support.text": "Wenn du den Support per E-Mail kontaktierst, erhalten wir die Informationen, die du sendest, etwa deine E-Mail-Adresse, Gerätedaten und Nachricht. Wir nutzen sie nur, um dir zu antworten.",
    "privacy.third.summary": "Dritte",
    "privacy.third.text": "Sidequest nutzt Apple-Dienste wie den App Store und iOS-Systemfunktionen. Für diese gelten die Datenschutzrichtlinien von Apple. Wir verkaufen deine persönlichen Daten nicht.",
    "privacy.delete.summary": "Daten löschen",
    "privacy.delete.text": "Die meisten App-Daten liegen lokal. Du entfernst sie, indem du die App löschst. Bei Fragen zu per E-Mail gesendeten Informationen kannst du den Support kontaktieren.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "Bei Datenschutzfragen schreib an pcesnek290@gmail.com.",
    "quest.title": "Du wurdest herausgefordert ⚔️",
    "quest.text": "Ein Freund fordert dich zu diesem Quest heraus. Sidequest wird geöffnet…",
    "quest.open": "In der App öffnen",
    "quest.store": "Kein Sidequest? Hol es dir im App Store"
  },
  es: {
    "nav.features": "Funciones",
    "nav.support": "Soporte",
    "nav.privacy": "Privacidad",
    "hero.eyebrow": "App para iPhone",
    "hero.title": "Sidequest",
    "hero.text": "La vida es corta. Haz algo raro con ella.",
    "hero.cta": "Descargar en el App Store",
    "hero.support": "Obtener soporte",
    "preview.title": "Tu misión es:",
    "preview.category": "Exploración",
    "preview.difficulty": "Algo Incómodo",
    "preview.questTitle": "Encuentra el mejor café de una ciudad que no sea la tuya",
    "preview.questText": "Pregúntale a alguien del lugar. No a Google.",
    "preview.question": "¿Aceptas?",
    "preview.yes": "SÍ",
    "preview.no": "NO",
    "features.eyebrow": "Qué hace",
    "features.title": "Un pequeño empujón hacia el mundo real.",
    "features.generate.title": "Genera misiones",
    "features.generate.text": "Recibe retos concretos en las categorías social, culinaria, física, creativa, de exploración, mecánica y aleatoria.",
    "features.chronicles.title": "Construye crónicas",
    "features.chronicles.text": "Captura momentos de tus misiones con notas y hasta seis fotos por entrada, y revívelos en una vista de crónica a pantalla completa.",
    "features.badges.title": "Desbloquea logros",
    "features.badges.text": "Completa misiones, crea un historial y gana logros por las decisiones que ya explicarás después.",
    "features.memory.title": "Guarda la historia",
    "features.memory.text": "Añade una foto y una nota al completar una misión, y guárdala en tu historial o compártela.",
    "features.widget.title": "Mira tu misión de un vistazo",
    "features.widget.text": "Mantén la misión activa a la vista con el widget de iOS y el soporte de Live Activity.",
    "features.filters.title": "Controla el catálogo",
    "features.filters.text": "Elige categorías y niveles de dificultad, y bloquea las palabras que no quieras ver.",
    "features.premium.title": "Desbloquea Premium",
    "features.premium.text": "Premium desbloquea la dificultad Locura Total, drops exclusivos BSC y los futuros packs de misiones.",
    "premium.eyebrow": "Premium",
    "premium.title": "Desata el caos.",
    "premium.text": "Las misiones gratuitas son lo seguro. Con Premium es donde Sidequest se pone interesante.",
    "premium.chip1": "Dificultad Locura Total",
    "premium.chip2": "Drops exclusivos de misiones BSC",
    "premium.chip3": "Futuros packs de misiones incluidos",
    "levels.eyebrow": "Niveles de dificultad",
    "levels.title": "De lo inofensivo a lo muy cuestionable.",
    "levels.text": "Ajusta tu zona de confort. Sidequest tiene cuatro niveles de dificultad, y Locura Total está disponible con Premium.",
    "levels.safe": "Divertido y Seguro",
    "levels.mild": "Algo Incómodo",
    "levels.probably": "Mejor No Deberías",
    "levels.bsc": "Locura Total",
    "download.title": "Disponible en el App Store.",
    "download.text": "Descarga Sidequest para iPhone y empieza tu próxima misión en el mundo real.",
    "download.button": "Abrir App Store",
    "footer.support": "Soporte",
    "footer.marketing": "Página de marketing",
    "footer.privacy": "Privacidad",
    "support.eyebrow": "Soporte",
    "support.title": "Soporte de Sidequest",
    "support.intro": "¿Necesitas ayuda con la app, las suscripciones, el historial de misiones, los logros o algo que no cuadra? Empieza aquí.",
    "support.contact.title": "Contacto",
    "support.contact.text": "Para soporte de la app, incluye el modelo de tu dispositivo, la versión de iOS y una breve descripción del problema.",
    "support.contact.button": "Escribir a soporte",
    "support.contact.note": "Correo de soporte actual: pcesnek290@gmail.com",
    "support.restore.title": "Compras",
    "support.restore.text": "Si te falta el acceso premium tras reinstalar o cambiar de dispositivo, abre los ajustes de Sidequest y usa Restaurar compras.",
    "support.data.title": "Fotos e historial",
    "support.data.text": "El historial de misiones, las notas, los logros y las entradas de crónica se guardan en tu dispositivo. Las fotos de las crónicas usan tu galería de Fotos de iOS.",
    "support.safety.title": "Seguridad en las misiones",
    "support.safety.text": "Usa el sentido común, respeta las leyes locales y salta cualquier misión que te parezca insegura, ilegal o inadecuada para tu situación.",
    "support.remote.title": "Packs de misiones",
    "support.remote.text": "Sidequest puede descargar el catálogo de misiones más reciente desde el repositorio de misiones de Sidequest. Si no hay red, la app puede usar las misiones incluidas o en caché.",
    "support.activity.title": "Widget y Live Activity",
    "support.activity.text": "Si una misión activa no aparece en el widget o en Live Activity, abre la app una vez e inicia o restaura la misión actual.",
    "faq.title": "Preguntas frecuentes",
    "faq.block.summary": "¿Puedo bloquear misiones que no quiero?",
    "faq.block.text": "Sí. En los ajustes puedes desactivar categorías o añadir palabras bloqueadas.",
    "faq.languages.summary": "¿Qué idiomas están disponibles?",
    "faq.languages.text": "Sidequest está localizado en inglés, checo, eslovaco, alemán, español y portugués.",
    "faq.widget.summary": "¿Sidequest tiene widget?",
    "faq.widget.text": "Sí. El widget y Live Activity pueden mostrar tu misión activa de un vistazo.",
    "faq.premium.summary": "¿Qué desbloquea Premium?",
    "faq.premium.text": "Premium desbloquea la dificultad Locura Total, drops exclusivos de misiones BSC y los futuros packs de misiones.",
    "privacy.eyebrow": "Privacidad",
    "privacy.title": "Política de privacidad",
    "privacy.updated": "Última actualización: 19 de junio de 2026",
    "privacy.overview.title": "Resumen",
    "privacy.overview.text": "Sidequest está diseñado para que tu actividad personal de misiones se quede en tu dispositivo. No tenemos sistema de cuentas propio, red publicitaria ni servicio de analítica dentro de la app.",
    "privacy.collect.summary": "Información que guarda la app",
    "privacy.collect.text": "Sidequest puede guardar localmente en tu dispositivo tu nombre visible, tus preferencias, las misiones generadas, el estado de la misión activa, el historial de misiones, los logros, las palabras bloqueadas, las notas, las entradas de crónica y las referencias a fotos, para que la app pueda funcionar.",
    "privacy.photos.summary": "Fotos y acceso a la cámara",
    "privacy.photos.text": "Si decides añadir fotos a una misión o a una entrada de crónica, Sidequest usa el acceso a la cámara o a la galería solo para esa acción. Las entradas de crónica pueden guardar identificadores locales de la galería de Fotos para que la app pueda mostrarlas después.",
    "privacy.remote.summary": "Descargas de misiones",
    "privacy.remote.text": "Sidequest puede contactar con el repositorio de misiones de Sidequest para descargar el catálogo más reciente y guardarlo en caché en tu dispositivo. Esta petición es para el contenido de la app, no para sincronizar una cuenta de usuario.",
    "privacy.purchases.summary": "Compras y suscripciones",
    "privacy.purchases.text": "Las compras premium las procesa Apple a través del App Store. Sidequest puede leer el estado de tus compras en el App Store para desbloquear funciones premium, pero los datos de pago los gestiona Apple.",
    "privacy.support.summary": "Correo de soporte",
    "privacy.support.text": "Si contactas con soporte por correo, recibimos la información que decidas enviar, como tu dirección de correo, los datos del dispositivo y tu mensaje. La usamos solo para responderte.",
    "privacy.third.summary": "Terceros",
    "privacy.third.text": "Sidequest usa servicios de Apple como el App Store y funciones del sistema iOS. Esos servicios se rigen por las políticas de privacidad de Apple. No vendemos tu información personal.",
    "privacy.delete.summary": "Eliminar tus datos",
    "privacy.delete.text": "La mayoría de los datos de la app se guardan localmente. Puedes eliminarlos borrando la app de tu dispositivo. También puedes contactar con soporte si tienes dudas sobre la información enviada por correo.",
    "privacy.contact.summary": "Contacto",
    "privacy.contact.text": "Para preguntas sobre privacidad, escribe a pcesnek290@gmail.com.",
    "quest.title": "Te han retado ⚔️",
    "quest.text": "Un amigo te reta a hacer esta misión. Abriendo Sidequest…",
    "quest.open": "Abrir en la app",
    "quest.store": "¿No tienes Sidequest? Consíguelo en el App Store"
  },
  pt: {
    "nav.features": "Funcionalidades",
    "nav.support": "Apoio",
    "nav.privacy": "Privacidade",
    "hero.eyebrow": "App para iPhone",
    "hero.title": "Sidequest",
    "hero.text": "A vida é curta. Faz algo estranho com ela.",
    "hero.cta": "Descarregar na App Store",
    "hero.support": "Obter apoio",
    "preview.title": "A tua missão é:",
    "preview.category": "Exploração",
    "preview.difficulty": "Ligeiramente Incómodo",
    "preview.questTitle": "Encontra o melhor café numa cidade que não é a tua",
    "preview.questText": "Pergunta a um local. Não ao Google.",
    "preview.question": "Aceitas?",
    "preview.yes": "SIM",
    "preview.no": "NÃO",
    "features.eyebrow": "O que faz",
    "features.title": "Um pequeno empurrão para o mundo real.",
    "features.generate.title": "Gera missões",
    "features.generate.text": "Recebe desafios concretos nas categorias social, culinária, física, criativa, de exploração, mecânica e aleatória.",
    "features.chronicles.title": "Constrói crónicas",
    "features.chronicles.text": "Captura momentos das tuas missões com notas e até seis fotos por entrada, e revê-os numa vista de crónica em ecrã inteiro.",
    "features.badges.title": "Desbloqueia conquistas",
    "features.badges.text": "Completa missões, cria um histórico e ganha conquistas pelas decisões que explicarás mais tarde.",
    "features.memory.title": "Guarda a história",
    "features.memory.text": "Adiciona uma foto e uma nota ao concluir uma missão e guarda-a no teu histórico ou partilha-a.",
    "features.widget.title": "Vê a missão num relance",
    "features.widget.text": "Mantém a missão ativa à vista com o widget do iOS e o suporte de Live Activity.",
    "features.filters.title": "Controla o catálogo",
    "features.filters.text": "Escolhe categorias e níveis de dificuldade e bloqueia as palavras que não queres ver.",
    "features.premium.title": "Desbloqueia o Premium",
    "features.premium.text": "O Premium desbloqueia a dificuldade Loucura Total, drops exclusivos BSC e os futuros packs de missões.",
    "premium.eyebrow": "Premium",
    "premium.title": "Desencadeia o caos.",
    "premium.text": "As missões gratuitas são o lado seguro. É com o Premium que o Sidequest fica interessante.",
    "premium.chip1": "Dificuldade Loucura Total",
    "premium.chip2": "Drops exclusivos de missões BSC",
    "premium.chip3": "Futuros packs de missões incluídos",
    "levels.eyebrow": "Níveis de dificuldade",
    "levels.title": "Do inofensivo ao altamente questionável.",
    "levels.text": "Ajusta a tua zona de conforto. O Sidequest tem quatro níveis de dificuldade, e Loucura Total está disponível com o Premium.",
    "levels.safe": "Divertido e Seguro",
    "levels.mild": "Ligeiramente Incómodo",
    "levels.probably": "Melhor Não Devias",
    "levels.bsc": "Loucura Total",
    "download.title": "Disponível na App Store.",
    "download.text": "Descarrega o Sidequest para iPhone e começa a tua próxima missão no mundo real.",
    "download.button": "Abrir a App Store",
    "footer.support": "Apoio",
    "footer.marketing": "Página de marketing",
    "footer.privacy": "Privacidade",
    "support.eyebrow": "Apoio",
    "support.title": "Apoio do Sidequest",
    "support.intro": "Precisas de ajuda com a app, as subscrições, o histórico de missões, as conquistas ou algo que não parece bem? Começa aqui.",
    "support.contact.title": "Contacto",
    "support.contact.text": "Para apoio à app, indica o modelo do teu dispositivo, a versão do iOS e uma breve descrição do problema.",
    "support.contact.button": "Enviar email ao apoio",
    "support.contact.note": "Email de apoio atual: pcesnek290@gmail.com",
    "support.restore.title": "Compras",
    "support.restore.text": "Se te faltar o acesso premium depois de reinstalar ou mudar de dispositivo, abre as definições do Sidequest e usa Restaurar compras.",
    "support.data.title": "Fotos e histórico",
    "support.data.text": "O histórico de missões, as notas, as conquistas e as entradas de crónica são guardados no teu dispositivo. As fotos das crónicas usam a tua biblioteca de Fotos do iOS.",
    "support.safety.title": "Segurança nas missões",
    "support.safety.text": "Usa o bom senso, respeita as leis locais e salta qualquer missão que te pareça insegura, ilegal ou inadequada para a tua situação.",
    "support.remote.title": "Packs de missões",
    "support.remote.text": "O Sidequest pode descarregar o catálogo de missões mais recente a partir do repositório de missões do Sidequest. Se não houver rede, a app pode usar as missões incluídas ou em cache.",
    "support.activity.title": "Widget e Live Activity",
    "support.activity.text": "Se uma missão ativa não aparecer no widget ou na Live Activity, abre a app uma vez e inicia ou restaura a missão atual.",
    "faq.title": "Perguntas frequentes",
    "faq.block.summary": "Posso bloquear missões que não quero?",
    "faq.block.text": "Sim. Nas definições podes desativar categorias ou adicionar palavras bloqueadas.",
    "faq.languages.summary": "Que idiomas são suportados?",
    "faq.languages.text": "O Sidequest está localizado em inglês, checo, eslovaco, alemão, espanhol e português.",
    "faq.widget.summary": "O Sidequest tem widget?",
    "faq.widget.text": "Sim. O widget e a Live Activity podem mostrar a tua missão ativa num relance.",
    "faq.premium.summary": "O que é que o Premium desbloqueia?",
    "faq.premium.text": "O Premium desbloqueia a dificuldade Loucura Total, drops exclusivos de missões BSC e os futuros packs de missões.",
    "privacy.eyebrow": "Privacidade",
    "privacy.title": "Política de privacidade",
    "privacy.updated": "Última atualização: 19 de junho de 2026",
    "privacy.overview.title": "Visão geral",
    "privacy.overview.text": "O Sidequest foi concebido para manter a tua atividade pessoal de missões no teu dispositivo. Não temos sistema de contas próprio, rede publicitária nem serviço de estatísticas dentro da app.",
    "privacy.collect.summary": "Informação que a app guarda",
    "privacy.collect.text": "O Sidequest pode guardar localmente no teu dispositivo o teu nome visível, as tuas preferências, as missões geradas, o estado da missão ativa, o histórico de missões, as conquistas, as palavras bloqueadas, as notas, as entradas de crónica e as referências a fotos, para que a app possa funcionar.",
    "privacy.photos.summary": "Fotos e acesso à câmara",
    "privacy.photos.text": "Se optares por adicionar fotos a uma missão ou a uma entrada de crónica, o Sidequest usa o acesso à câmara ou à galeria apenas para essa ação. As entradas de crónica podem guardar identificadores locais da biblioteca de Fotos para que a app possa mostrá-las mais tarde.",
    "privacy.remote.summary": "Descarregamento de missões",
    "privacy.remote.text": "O Sidequest pode contactar o repositório de missões do Sidequest para descarregar o catálogo mais recente e guardá-lo em cache no teu dispositivo. Este pedido serve o conteúdo da app, não a sincronização de uma conta de utilizador.",
    "privacy.purchases.summary": "Compras e subscrições",
    "privacy.purchases.text": "As compras premium são processadas pela Apple através da App Store. O Sidequest pode ler o estado das tuas compras na App Store para desbloquear funcionalidades premium, mas os dados de pagamento são geridos pela Apple.",
    "privacy.support.summary": "Email de apoio",
    "privacy.support.text": "Se contactares o apoio por email, recebemos a informação que decidires enviar, como o teu endereço de email, os dados do dispositivo e a tua mensagem. Usamo-la apenas para te responder.",
    "privacy.third.summary": "Terceiros",
    "privacy.third.text": "O Sidequest usa serviços da Apple, como a App Store e funcionalidades do sistema iOS. Esses serviços regem-se pelas políticas de privacidade da Apple. Não vendemos a tua informação pessoal.",
    "privacy.delete.summary": "Eliminar os teus dados",
    "privacy.delete.text": "A maioria dos dados da app fica guardada localmente. Podes removê-los apagando a app do teu dispositivo. Também podes contactar o apoio se tiveres dúvidas sobre a informação enviada por email.",
    "privacy.contact.summary": "Contacto",
    "privacy.contact.text": "Para questões de privacidade, escreve para pcesnek290@gmail.com.",
    "quest.title": "Foste desafiado ⚔️",
    "quest.text": "Um amigo desafia-te a fazer esta missão. A abrir o Sidequest…",
    "quest.open": "Abrir na app",
    "quest.store": "Não tens o Sidequest? Obtém-no na App Store"
  }
};

const supportedLanguages = Object.keys(translations);
const browserLanguage = navigator.language.slice(0, 2);
const savedLanguage = localStorage.getItem("sidequest-language");
const initialLanguage = supportedLanguages.includes(savedLanguage)
  ? savedLanguage
  : supportedLanguages.includes(browserLanguage)
    ? browserLanguage
    : "en";

function setLanguage(language) {
  const dictionary = translations[language] || translations.en;
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) {
      element.textContent = dictionary[key];
    }
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === language);
    button.setAttribute("aria-pressed", String(button.dataset.lang === language));
  });
  localStorage.setItem("sidequest-language", language);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(initialLanguage);
