const translations = {
  en: {
    "nav.features": "Features",
    "nav.support": "Support",
    "nav.privacy": "Privacy",
    "hero.eyebrow": "iPhone app",
    "hero.title": "Sidequest",
    "hero.text": "Quests that make a great story. Or a great excuse.",
    "hero.cta": "Coming to the App Store",
    "hero.support": "Get support",
    "preview.title": "Your side quest is:",
    "preview.category": "Exploration",
    "preview.difficulty": "Mildly Inconvenient",
    "preview.questTitle": "Find the best coffee in a city that is not yours",
    "preview.questText": "Ask a local. Not Google.",
    "preview.question": "Do you accept?",
    "preview.yes": "YES",
    "preview.no": "NO",
    "features.eyebrow": "What it does",
    "features.title": "A tiny push into the real world.",
    "features.generate.title": "Generate quests",
    "features.generate.text": "Get a concrete challenge across social, culinary, physical, creative, exploration, mechanical, and random categories.",
    "features.badges.title": "Unlock badges",
    "features.badges.text": "Complete quests, build a history, and earn badges for the choices you can proudly explain later.",
    "features.memory.title": "Save the story",
    "features.memory.text": "Add a photo and note when a quest is complete, then keep it in your history or share it.",
    "levels.eyebrow": "Difficulty levels",
    "levels.title": "From harmless to highly questionable.",
    "levels.text": "Tune your comfort zone, block topics you do not want, and keep the app playful without losing control.",
    "levels.safe": "Fun & Safe",
    "levels.mild": "Mildly Inconvenient",
    "levels.probably": "Probably Shouldn't",
    "levels.bsc": "Bat Shit Crazy",
    "download.title": "Ready for App Store review.",
    "download.text": "Use this page as your Marketing URL. Use the support page as your Support URL.",
    "footer.support": "Support",
    "footer.marketing": "Marketing page",
    "footer.privacy": "Privacy",
    "support.eyebrow": "Support",
    "support.title": "Sidequest Support",
    "support.intro": "Need help with the app, subscriptions, quest history, badges, or something that feels off? Start here.",
    "support.contact.title": "Contact",
    "support.contact.text": "For app support, include your device model, iOS version, and a short description of the issue.",
    "support.contact.button": "Email support",
    "support.contact.note": "Current support email: pcesnek290@gmail.com",
    "support.restore.title": "Purchases",
    "support.restore.text": "If premium access is missing after reinstalling or changing devices, open Sidequest settings and use Restore Purchases.",
    "support.data.title": "Photos and history",
    "support.data.text": "Quest notes and photos are stored on your device. If you delete the app, local data may be removed by iOS.",
    "support.safety.title": "Quest safety",
    "support.safety.text": "Use judgement, follow local laws, and skip any quest that feels unsafe, illegal, or inappropriate for your situation.",
    "faq.title": "FAQ",
    "faq.block.summary": "Can I block quests I do not want?",
    "faq.block.text": "Yes. In settings, you can disable categories or add blocked keywords.",
    "faq.languages.summary": "Which languages are supported?",
    "faq.languages.text": "Sidequest is localized in English, Czech, and Slovak.",
    "faq.widget.summary": "Does Sidequest have a widget?",
    "faq.widget.text": "Yes. The widget can show your current active quest at a glance.",
    "privacy.eyebrow": "Privacy",
    "privacy.title": "Privacy Policy",
    "privacy.updated": "Last updated: May 10, 2026",
    "privacy.overview.title": "Overview",
    "privacy.overview.text": "Sidequest is designed to keep your quest activity on your device. We do not run our own account system, advertising network, or analytics service in the app.",
    "privacy.collect.summary": "Information the app stores",
    "privacy.collect.text": "Sidequest may store your display name, preferences, generated quests, quest history, badges, blocked keywords, notes, and quest photos locally on your device so the app can work.",
    "privacy.photos.summary": "Photos and camera access",
    "privacy.photos.text": "If you choose to add a photo to a completed quest, the photo is used for that quest history entry. Photos remain on your device unless you choose to share them through iOS sharing features.",
    "privacy.purchases.summary": "Purchases and subscriptions",
    "privacy.purchases.text": "Premium purchases are processed by Apple through the App Store. Sidequest may read your App Store purchase status to unlock premium features, but payment details are handled by Apple.",
    "privacy.support.summary": "Support email",
    "privacy.support.text": "If you contact support by email, we receive the information you choose to send, such as your email address, device details, and message. We use it only to respond to your request.",
    "privacy.third.summary": "Third parties",
    "privacy.third.text": "Sidequest uses Apple services such as the App Store and iOS system features. Those services are governed by Apple's privacy policies. We do not sell your personal information.",
    "privacy.delete.summary": "Deleting your data",
    "privacy.delete.text": "Most app data is stored locally. You can remove it by deleting the app from your device. You can also contact support if you have questions about information sent by email.",
    "privacy.contact.summary": "Contact",
    "privacy.contact.text": "For privacy questions, email pcesnek290@gmail.com."
  },
  cs: {
    "nav.features": "Funkce",
    "nav.support": "Podpora",
    "nav.privacy": "Soukromí",
    "hero.eyebrow": "iPhone aplikace",
    "hero.title": "Sidequest",
    "hero.text": "Questy, ze kterých bude skvělý příběh. Nebo skvělá výmluva.",
    "hero.cta": "Již brzy v App Storu",
    "hero.support": "Získat podporu",
    "preview.title": "Tvůj sidequest je:",
    "preview.category": "Průzkum",
    "preview.difficulty": "Mírně nepohodlné",
    "preview.questTitle": "Najdi nejlepší kávu ve městě, které není tvoje",
    "preview.questText": "Zeptej se místního. Ne Googlu.",
    "preview.question": "Přijímáš?",
    "preview.yes": "ANO",
    "preview.no": "NE",
    "features.eyebrow": "Co umí",
    "features.title": "Malé pošťouchnutí do skutečného světa.",
    "features.generate.title": "Generuj questy",
    "features.generate.text": "Získej konkrétní výzvu ze sociálních, kulinářských, fyzických, kreativních, průzkumných, mechanických a náhodných kategorií.",
    "features.badges.title": "Odemykej odznaky",
    "features.badges.text": "Plň questy, buduj historii a sbírej odznaky za rozhodnutí, která později zvládneš hrdě vysvětlit.",
    "features.memory.title": "Ulož si příběh",
    "features.memory.text": "Po dokončení přidej fotku a poznámku, nech si je v historii nebo je sdílej.",
    "levels.eyebrow": "Obtížnosti",
    "levels.title": "Od neškodného po silně pochybné.",
    "levels.text": "Nastav si komfortní zónu, blokuj témata, která nechceš, a nech aplikaci hravou bez ztráty kontroly.",
    "levels.safe": "Zábavné a bezpečné",
    "levels.mild": "Mírně nepohodlné",
    "levels.probably": "Radši asi ne",
    "levels.bsc": "Šílené",
    "download.title": "Připraveno pro App Store review.",
    "download.text": "Tuto stránku použij jako Marketing URL. Stránku podpory použij jako Support URL.",
    "footer.support": "Podpora",
    "footer.marketing": "Marketingová stránka",
    "footer.privacy": "Soukromí",
    "support.eyebrow": "Podpora",
    "support.title": "Podpora Sidequest",
    "support.intro": "Potřebuješ pomoc s aplikací, předplatným, historií questů, odznaky nebo něčím, co nefunguje správně? Začni tady.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Pro podporu uveď model zařízení, verzi iOS a krátký popis problému.",
    "support.contact.button": "Napsat podpoře",
    "support.contact.note": "Aktuální e-mail podpory: pcesnek290@gmail.com",
    "support.restore.title": "Nákupy",
    "support.restore.text": "Pokud po přeinstalaci nebo změně zařízení chybí premium přístup, otevři nastavení Sidequestu a použij Obnovit nákupy.",
    "support.data.title": "Fotky a historie",
    "support.data.text": "Poznámky a fotky ke questům jsou uložené v zařízení. Pokud aplikaci smažeš, iOS může lokální data odstranit.",
    "support.safety.title": "Bezpečnost questů",
    "support.safety.text": "Používej úsudek, dodržuj místní zákony a přeskoč každý quest, který je nebezpečný, nelegální nebo nevhodný pro tvoji situaci.",
    "faq.title": "FAQ",
    "faq.block.summary": "Můžu blokovat questy, které nechci?",
    "faq.block.text": "Ano. V nastavení můžeš vypnout kategorie nebo přidat blokovaná klíčová slova.",
    "faq.languages.summary": "Jaké jazyky aplikace podporuje?",
    "faq.languages.text": "Sidequest je lokalizovaný do angličtiny, češtiny a slovenštiny.",
    "faq.widget.summary": "Má Sidequest widget?",
    "faq.widget.text": "Ano. Widget umí zobrazit aktuální aktivní quest na první pohled.",
    "privacy.eyebrow": "Soukromí",
    "privacy.title": "Zásady ochrany soukromí",
    "privacy.updated": "Naposledy aktualizováno: 10. května 2026",
    "privacy.overview.title": "Přehled",
    "privacy.overview.text": "Sidequest je navržený tak, aby tvoje aktivita v questech zůstávala v zařízení. V aplikaci neprovozujeme vlastní systém účtů, reklamní síť ani analytickou službu.",
    "privacy.collect.summary": "Informace uložené aplikací",
    "privacy.collect.text": "Sidequest může lokálně v zařízení ukládat tvoje zobrazované jméno, preference, vygenerované questy, historii questů, odznaky, blokovaná klíčová slova, poznámky a fotky ke questům, aby aplikace mohla fungovat.",
    "privacy.photos.summary": "Fotky a přístup ke kameře",
    "privacy.photos.text": "Pokud se rozhodneš přidat fotku k dokončenému questu, fotka se použije pro daný záznam v historii. Fotky zůstávají v zařízení, pokud se je nerozhodneš sdílet přes systémové funkce iOS.",
    "privacy.purchases.summary": "Nákupy a předplatná",
    "privacy.purchases.text": "Prémiové nákupy zpracovává Apple prostřednictvím App Storu. Sidequest může číst stav nákupu z App Storu pro odemčení prémiových funkcí, ale platební údaje zpracovává Apple.",
    "privacy.support.summary": "E-mail podpory",
    "privacy.support.text": "Pokud kontaktuješ podporu e-mailem, obdržíme informace, které se rozhodneš poslat, například e-mailovou adresu, údaje o zařízení a zprávu. Použijeme je pouze k odpovědi na tvůj požadavek.",
    "privacy.third.summary": "Třetí strany",
    "privacy.third.text": "Sidequest používá služby Apple, například App Store a systémové funkce iOS. Tyto služby se řídí zásadami ochrany soukromí společnosti Apple. Tvoje osobní informace neprodáváme.",
    "privacy.delete.summary": "Smazání dat",
    "privacy.delete.text": "Většina dat aplikace je uložená lokálně. Můžeš je odstranit smazáním aplikace ze zařízení. Pokud máš otázky k informacím poslaným e-mailem, můžeš kontaktovat podporu.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "S otázkami k soukromí napiš na pcesnek290@gmail.com."
  },
  sk: {
    "nav.features": "Funkcie",
    "nav.support": "Podpora",
    "nav.privacy": "Súkromie",
    "hero.eyebrow": "iPhone aplikácia",
    "hero.title": "Sidequest",
    "hero.text": "Questy, z ktorých bude skvelý príbeh. Alebo skvelá výhovorka.",
    "hero.cta": "Už čoskoro v App Store",
    "hero.support": "Získať podporu",
    "preview.title": "Tvoj sidequest je:",
    "preview.category": "Prieskum",
    "preview.difficulty": "Mierne nepohodlné",
    "preview.questTitle": "Nájdi najlepšiu kávu v meste, ktoré nie je tvoje",
    "preview.questText": "Spýtaj sa miestneho. Nie Googlu.",
    "preview.question": "Prijímaš?",
    "preview.yes": "ÁNO",
    "preview.no": "NIE",
    "features.eyebrow": "Čo robí",
    "features.title": "Malé postrčenie do skutočného sveta.",
    "features.generate.title": "Generuj questy",
    "features.generate.text": "Získaj konkrétnu výzvu zo sociálnych, kulinárskych, fyzických, kreatívnych, prieskumných, mechanických a náhodných kategórií.",
    "features.badges.title": "Odomykaj odznaky",
    "features.badges.text": "Plň questy, buduj históriu a získavaj odznaky za rozhodnutia, ktoré neskôr zvládneš hrdo vysvetliť.",
    "features.memory.title": "Ulož si príbeh",
    "features.memory.text": "Po dokončení pridaj fotku a poznámku, nechaj si ich v histórii alebo ich zdieľaj.",
    "levels.eyebrow": "Obtiažnosti",
    "levels.title": "Od neškodného po silne otázne.",
    "levels.text": "Nastav si komfortnú zónu, blokuj témy, ktoré nechceš, a nechaj aplikáciu hravú bez straty kontroly.",
    "levels.safe": "Zábavné a bezpečné",
    "levels.mild": "Mierne nepohodlné",
    "levels.probably": "Radšej asi nie",
    "levels.bsc": "Šialené",
    "download.title": "Pripravené pre App Store review.",
    "download.text": "Túto stránku použi ako Marketing URL. Stránku podpory použi ako Support URL.",
    "footer.support": "Podpora",
    "footer.marketing": "Marketingová stránka",
    "footer.privacy": "Súkromie",
    "support.eyebrow": "Podpora",
    "support.title": "Podpora Sidequest",
    "support.intro": "Potrebuješ pomoc s aplikáciou, predplatným, históriou questov, odznakmi alebo niečím, čo nefunguje správne? Začni tu.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Pre podporu uveď model zariadenia, verziu iOS a krátky popis problému.",
    "support.contact.button": "Napísať podpore",
    "support.contact.note": "Aktuálny e-mail podpory: pcesnek290@gmail.com",
    "support.restore.title": "Nákupy",
    "support.restore.text": "Ak po preinštalovaní alebo zmene zariadenia chýba premium prístup, otvor nastavenia Sidequestu a použi Obnoviť nákupy.",
    "support.data.title": "Fotky a história",
    "support.data.text": "Poznámky a fotky ku questom sú uložené v zariadení. Ak aplikáciu vymažeš, iOS môže lokálne dáta odstrániť.",
    "support.safety.title": "Bezpečnosť questov",
    "support.safety.text": "Používaj úsudok, dodržiavaj miestne zákony a preskoč každý quest, ktorý je nebezpečný, nelegálny alebo nevhodný pre tvoju situáciu.",
    "faq.title": "FAQ",
    "faq.block.summary": "Môžem blokovať questy, ktoré nechcem?",
    "faq.block.text": "Áno. V nastaveniach môžeš vypnúť kategórie alebo pridať blokované kľúčové slová.",
    "faq.languages.summary": "Aké jazyky aplikácia podporuje?",
    "faq.languages.text": "Sidequest je lokalizovaný do angličtiny, češtiny a slovenčiny.",
    "faq.widget.summary": "Má Sidequest widget?",
    "faq.widget.text": "Áno. Widget vie zobraziť aktuálny aktívny quest na prvý pohľad.",
    "privacy.eyebrow": "Súkromie",
    "privacy.title": "Zásady ochrany súkromia",
    "privacy.updated": "Naposledy aktualizované: 10. mája 2026",
    "privacy.overview.title": "Prehľad",
    "privacy.overview.text": "Sidequest je navrhnutý tak, aby tvoja aktivita v questoch zostávala v zariadení. V aplikácii neprevádzkujeme vlastný systém účtov, reklamnú sieť ani analytickú službu.",
    "privacy.collect.summary": "Informácie uložené aplikáciou",
    "privacy.collect.text": "Sidequest môže lokálne v zariadení ukladať tvoje zobrazované meno, preferencie, vygenerované questy, históriu questov, odznaky, blokované kľúčové slová, poznámky a fotky ku questom, aby aplikácia mohla fungovať.",
    "privacy.photos.summary": "Fotky a prístup ku kamere",
    "privacy.photos.text": "Ak sa rozhodneš pridať fotku k dokončenému questu, fotka sa použije pre daný záznam v histórii. Fotky zostávajú v zariadení, pokiaľ sa ich nerozhodneš zdieľať cez systémové funkcie iOS.",
    "privacy.purchases.summary": "Nákupy a predplatné",
    "privacy.purchases.text": "Prémiové nákupy spracúva Apple prostredníctvom App Store. Sidequest môže čítať stav nákupu z App Store na odomknutie prémiových funkcií, ale platobné údaje spracúva Apple.",
    "privacy.support.summary": "E-mail podpory",
    "privacy.support.text": "Ak kontaktuješ podporu e-mailom, dostaneme informácie, ktoré sa rozhodneš poslať, napríklad e-mailovú adresu, údaje o zariadení a správu. Použijeme ich iba na odpoveď na tvoju požiadavku.",
    "privacy.third.summary": "Tretie strany",
    "privacy.third.text": "Sidequest používa služby Apple, napríklad App Store a systémové funkcie iOS. Tieto služby sa riadia zásadami ochrany súkromia spoločnosti Apple. Tvoje osobné informácie nepredávame.",
    "privacy.delete.summary": "Vymazanie dát",
    "privacy.delete.text": "Väčšina dát aplikácie je uložená lokálne. Môžeš ich odstrániť vymazaním aplikácie zo zariadenia. Ak máš otázky k informáciám poslaným e-mailom, môžeš kontaktovať podporu.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "S otázkami k súkromiu napíš na pcesnek290@gmail.com."
  }
};

const supportedLanguages = Object.keys(translations);
const browserLanguage = navigator.language.slice(0, 2);
const savedLanguage = localStorage.getItem("sidequest-language");
const initialLanguage = supportedLanguages.includes(savedLanguage)
  ? savedLanguage
  : supportedLanguages.includes(browserLanguage)
    ? browserLanguage
    : "en";

function setLanguage(language) {
  const dictionary = translations[language] || translations.en;
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) {
      element.textContent = dictionary[key];
    }
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === language);
    button.setAttribute("aria-pressed", String(button.dataset.lang === language));
  });
  localStorage.setItem("sidequest-language", language);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(initialLanguage);
